spring.application.name=Email-Service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/emailService
spring.datasource.username=postgres
spring.datasource.password=2000319

#jpa vendor adapter configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html




logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# MailHog SMTP configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false



# http://localhost:8025/---------mailhog web ui

# Brevo SMTP configuration
#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#spring.mail.username=8558fa001@smtp-brevo.com
#spring.mail.password=bPBRzTrmJwhYFa3n
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
# Enable SMTP debug logging
#spring.mail.properties.mail.debug=true

#brevo.api.key=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